INSERT INTO regras (id_regra, regra, id_propriedade) VALUES
(1, 'Proibido fumar nas dependências', 1),
(2, 'Não é permitido fazer festas ou eventos', 2),
(3, 'Animais de estimação não são permitidos', 3),
(4, 'Check-in após as 14:00 e check-out até às 12:00', 4),
(5, 'É necessário apresentar documento de identidade no check-in', 5),
(6, 'A propriedade deve ser mantida limpa durante a estadia', 6),
(7, 'É proibido o uso de velas ou equipamentos de fogo', 7),
(8, 'O consumo de álcool é permitido apenas nas áreas externas', 8),
(9, 'Não são permitidos visitantes não registrados', 9),
(10, 'O uso de barbeadores e secadores de cabelo é restrito a áreas específicas', 10),
(11, 'Em caso de dano à propriedade, o hóspede será responsabilizado', 11),
(12, 'É proibido o uso de eletrodomésticos de alto consumo sem autorização', 12),
(13, 'A limpeza da casa será realizada apenas uma vez por semana', 13),
(14, 'Os hóspedes devem seguir as regras de silêncio entre 22:00 e 07:00', 14),
(15, 'A propriedade não oferece serviços de transporte', 15),
(16, 'O ar condicionado deve ser desligado quando não estiver em uso', 16),
(17, 'É permitido o uso de churrasqueira somente nas áreas externas', 17),
(18, 'Não é permitida a realização de modificações na decoração', 18),
(19, 'Os hóspedes devem respeitar o limite de ocupação da propriedade', 19),
(20, 'É proibido deixar lixo fora dos locais adequados', 20),
(21, 'A propriedade oferece estacionamento, sujeito à disponibilidade', 21),
(22, 'O hóspede deve fornecer informações de chegada com pelo menos 24 horas de antecedência', 22),
(23, 'O uso da piscina é permitido apenas durante o horário de funcionamento', 23),
(24, 'Não são permitidos animais domésticos sem autorização prévia', 24),
(25, 'A utilização da área de lazer é permitida apenas para os hóspedes registrados', 25),
(26, 'A propriedade não se responsabiliza por objetos esquecidos durante a estadia', 26),
(27, 'A vigilância por câmeras de segurança é feita apenas em áreas externas', 27),
(28, 'O uso de roupas de cama e banho é exclusivo da propriedade', 28),
(29, 'Os hóspedes devem cumprir as normas de segurança contra incêndio', 29),
(30, 'É proibido o uso de drogas ilícitas nas dependências da propriedade', 30);
